# Site settings
title: Scott Mathson, Web Guy
email: yo@scottmathson.com
description: "Scott Mathson, Web Guy. Optimizer, project manager, designer, & developer in Missoula, Montana. This page: a redesign and working prototype of Yelp."
baseurl: ""
url: "https://yelp.scottmathson.com"   # with the https protocol
enforce_ssl: yelp.scottmathson.com   # without any protocol

google_tracking_id: UA-76046814-3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

gems: ["jekyll-sitemap","jekyll-seo-tag","jekyll-feed", "jekyll-redirect-from"]

exclude: ["Gemfile","Gemfile.lock","README.md"]
